### ISSUE TITLE
version 0.29.11 (Latest)  cannot send input to console or debug

### ISSUE THREAD

**Issue by Chenthilraj** [erlide/erlide#219] opened 2015-05-07 09:12 UTC
Hi, I am using erlide latest version 0.29.11. Still I could not send input either from the console or from input window. I tried executing this command io:get_line("gissa line>"). and immediately I see, ok in the console. It is not waiting for user to provide input. Can you please help?

**Comment by vladdu** [comment] 2015-05-07 09:56
Hi, unfortunately io:get_line doean't work at the moment from the eclipse console. 

This is what you can do instead, for the time being: start an erlang node from the command line (must be distributed) and connect to it from Eclipse (by specifying its name and cookie in the "run configuration" dialog). All erlide features will still work, but you must interact with it from the command line.

Please let me know if you need further help.

**Comment by Chenthilraj** [comment] 2015-05-07 10:08
Thanks very much Vlad. Appreciate your quick response..

Thanks and Regards,
Chenthilraj

**Comment by vladdu** [comment] 2015-07-10 14:12
duplicate of #215

**Closed by vladdu** 2015-07-10 14:12 UTC
Labels: duplicate
